// Exact, evidence-backed model IDs for Contextimate's measured visible-text profiles.
// Keep dynamic aliases and unverified variants in heuristics.test.ts as negative cases.
export const tokenizerFamilies = [
  ["Kimi tokenizer", 4.1, 3.8, [
    "moonshotai/kimi-k2",
    "moonshotai/kimi-k2-0905-preview",
    "moonshotai/kimi-k2-thinking-turbo",
    "moonshotai/kimi-k2.5",
    "@cf/moonshotai/kimi-k2.6",
    "moonshotai/kimi-k2.7-code-highspeed",
    "accounts/fireworks/routers/kimi-k2p7-code-fast",
    "moonshotai/kimi-k3-fast",
  ]],
  ["GLM 4.5 tokenizer", 4, 3.9, [
    "z-ai/glm-4.5",
    "z-ai/glm-4.5-air",
    "z-ai/glm-4.5v",
    "z-ai/glm-4.6",
    "z-ai/glm-4.6v",
    "z-ai/glm-4.6v-flash",
    "zai-glm-4.7",
  ]],
  ["GLM 5 tokenizer", 4, 3.9, [
    "z-ai/glm-4.7-flash",
    "z-ai/glm-5",
    "z-ai/glm-5.1",
    "zai-org/glm-5.2",
    "accounts/fireworks/routers/glm-5p2-fast",
  ]],
  ["Command R tokenizer", 4, 3.4, [
    "cohere/command-r-08-2024",
    "cohere/command-r-plus-08-2024",
  ]],
  ["North Mini Code tokenizer", 4.2, 3.9, [
    "cohere/north-mini-code:free",
    "north-mini-code-free",
    "coherelabs/north-mini-code-1.0",
  ]],
  ["Grok 4.20/4.3 tokenizer", 4.2, 3.9, [
    "x-ai/grok-4.20",
    "xai/grok-4.20-reasoning",
    "xai/grok-4.20-non-reasoning",
    "grok-4.20-0309-reasoning",
    "grok-4.20-multi-agent-0309",
    "xai.grok-4.3",
    "grok-build-0.1",
  ]],
  ["Grok 4.5 tokenizer", 4.1, 3.6, ["x-ai/grok-4.5"]],
  ["Gemini 2/3 countTokens", 3.9, 3.4, [
    "gemini-2.0-flash",
    "google/gemini-2.0-flash-lite",
    "gemini-2.5-flash",
    "google/gemini-2.5-flash-lite:batch",
    "gemini-2.5-pro",
    "gemini-2.5-computer-use-preview-10-2025",
    "google/gemini-3-flash-preview:batch",
    "gemini-3-pro-preview",
    "google/gemini-3-pro-image",
    "gemini-3.1-flash-lite",
    "google/gemini-3.1-flash-lite-preview",
    "gemini-3.1-flash-lite-image",
    "google/gemini-3.1-pro-preview",
    "gemini-3.1-pro-preview-customtools",
    "google/gemini-3.5-flash:batch",
    "gemini-3.5-flash-lite",
    "google/gemini-3.6-flash:batch",
  ]],
  ["DeepSeek tokenizer", 4, 3.6, [
    "deepseek/deepseek-chat-v3-0324",
    "deepseek-ai/DeepSeek-R1",
    "deepseek/deepseek-r1-0528",
    "us.deepseek.r1-v1:0",
    "deepseek/deepseek-v3",
    "deepseek.v3-v1:0",
    "deepseek/deepseek-chat-v3.1",
    "deepseek/deepseek-v3.1-terminus",
    "deepseek/deepseek-v3.2-exp",
    "deepseek.v3.2",
    "deepseek/deepseek-v3.2-thinking",
    "deepseek-v4-flash-free",
    "deepseek/deepseek-v4-flash-0731",
    "deepseek-ai/DeepSeek-V4-Pro",
  ]],
  ["Qwen 2.5/3 tokenizer", 4, 3.8, [
    "qwen/qwen-2.5-7b-instruct",
    "qwen/qwen-2.5-72b-instruct",
    "Qwen/Qwen2.5-7B-Instruct-Turbo",
    "alibaba/qwen-3-14b",
    "alibaba/qwen-3-30b",
    "alibaba/qwen-3-235b",
    "@cf/qwen/qwen3-30b-a3b-fp8",
    "qwen/qwen3-235b-a22b-2507",
    "qwen.qwen3-235b-a22b-2507-v1:0",
    "Qwen/Qwen3-235B-A22B-Thinking-2507",
    "qwen.qwen3-next-80b-a3b",
    "qwen/qwen3-next-80b-a3b-thinking",
    "qwen.qwen3-coder-30b-a3b-v1:0",
    "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    "qwen/qwen3-coder-next",
    "qwen/qwen3-vl-8b-thinking",
    "qwen/qwen3-vl-30b-a3b-instruct",
    "qwen/qwen3-vl-32b-instruct",
    "qwen.qwen3-vl-235b-a22b",
  ]],
  ["Qwen 3.5 tokenizer", 3.9, 3.5, [
    "Qwen/Qwen3.5-9B",
    "qwen/qwen3.5-27b",
    "Qwen/Qwen3.5-35B-A3B",
    "qwen/qwen3.5-122b-a10b",
    "Qwen/Qwen3.5-397B-A17B",
  ]],
] as const;
